# Generated by Django 3.2.25 on 2024-06-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("text", models.TextField()),
                ("city", models.CharField(max_length=256, null=True)),
                ("area", models.CharField(max_length=256, null=True)),
                ("accented", models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
