# Generated by Django 3.2.25 on 2024-06-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='accented',
            field=models.BooleanField(null=True),
        ),
    ]
