# Generated by Django 3.2.25 on 2024-06-16 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_storytrigger"),
    ]

    operations = [
        migrations.RenameField(
            model_name="storytrigger",
            old_name="characters",
            new_name="setting",
        ),
    ]
