# Generated by Django 3.2.25 on 2024-06-17 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_rename_characters_storytrigger_setting"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="story_trigger",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.storytrigger",
            ),
        ),
    ]
