# Generated by Django 3.2.25 on 2024-06-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_story_story_trigger"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="area",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AlterField(
            model_name="story",
            name="city",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
    ]
